// data.js
const data = [
    "Pizza", 
    "Pasta", 
    "Pancake", 
    "Chicken curry", 
    "Beef stew", 
    "Fried rice", 
    "Salmon", 
    "Steak", 
    "Lemonade", 
    "Iced tea",
    "Apple pie",
    "Banana bread",
    "Cupcakes",
    "Doughnuts",
    "Eggs Benedict",
    "Fajitas",
    "Garlic bread",
    "Hamburgers",
    "Ice cream",
    "Jelly",
    "Kebabs",
    "Lasagna",
    "Muffins",
    "Nachos",
    "Omelette",
    "Pancakes",
    "Quiche",
    "Risotto",
    "Sandwich",
    "Tacos",
    "Udon",
    "Vegetable soup",
    "Waffles",
    "Xavier steak",
    "Yogurt",
    "Zucchini pasta"
];

export default data;
